# Based on https://github.com/commercialhaskell/stack/wiki/Travis

sudo: false # Use new caching docker based infrastructure
cache:
  directories:
  - $HOME/.stack
  - $HOME/.cabal

addons:
  apt:
    packages:
    - libgmp-dev
    - cabal-install-1.22
    - ghc-7.10.1
    sources:
    - hvr-ghc

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  # Work around the libexec path problem as per https://github.com/DanielG/cabal-helper/issues/7
  - export PATH=/opt/ghc/7.10.1/bin:$PATH
  - cabal-1.22 update
  - cabal-1.22 install cabal-helper
  # ghc
  # - export PATH=/opt/ghc/7.10.2/bin:$PATH

install:
  - ./travis_long stack --no-terminal setup
  - ./travis_long stack --no-terminal test --only-snapshot

script:
  - stack --no-terminal test


# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
# script:
#  - if [ -f configure.ac ]; then autoreconf -i; fi
#  - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
#  - cabal build   # this builds all libraries and executables (including tests/benchmarks)
#  - cabal test --show-details=streaming
#  - cabal check
#  - cabal sdist   # tests that a source-distribution can be generated



notifications:
  irc: "irc.freenode.org#haskell-refactorer"

