# NB: don't set `language: haskell` here

# See also https://github.com/hvr/multi-ghc-travis for more information
env:
 - CABALVER=1.22 GHCVER=head   # see section about GHC HEAD snapshots

# matrix:
#   allow_failures:
#    - env: GHCVER=head  CABALVER=1.20

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:/opt/cabal/1.22/bin/cabal:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - |
   git clone https://github.com/alanz/ghc-mod.git
   cd ghc-mod && git checkout ghc-7.10 && cabal install
   git clone https://github.com/alanz/hslogger.git
   cd hslogger && cabal install
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
 - cabal build   # this builds all libraries and executables (including tests/benchmarks)
 - cabal test
 - cabal check
 - cabal sdist   # tests that a source-distribution can be generated

# The following scriptlet checks that the resulting source distribution can be built & installed
 # - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
 #   cd dist/;
 #   if [ -f "$SRC_TGZ" ]; then
 #      cabal install --force-reinstalls "$SRC_TGZ";
 #   else
 #      echo "expected '$SRC_TGZ' not found";
 #      exit 1;


notifications:
  irc: "irc.freenode.org#haskell-refactorer"

